version: "3.8"
services:
  server:
    container_name: react-rest-service
    build:
      context: ./server
      dockerfile: Dockerfile
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
    ports:
      - "4000:4000"
    volumes:
      - ./server:/code:delegated
      - "/app/node_modules"
    networks:
      - reactapp-network
    depends_on:
      - db

  client:
    container_name: react-client-app
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/code:delegated
      - "/app/node_modules"
    networks:
      - reactapp-network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
      - MAILGUN_API_KEY=redis://cache
      - MAILGUN_API_DOMAIN=redis://cache
    volumes:
      - ./worker:/code:delegated
      - "/app/node_modules"
    networks:
      - reactapp-network
    depends_on:
      - db

  db:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - reactapp-network
    ports:
      - "27018:27017"

  redis:
    container_name: cache
    image: "redis:alpine"
    networks:
      - reactapp-network
    ports:
      - "6379:6379"

networks:
  reactapp-network:
    driver: bridge
