version: "3.8"
services:
  server:
    container_name: react-rest-service
    image: node:12-alpine
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
    ports:
      - "4000:4000"
    volumes:
      - ./server:/code:delegated
    networks:
      - reactapp-network
    working_dir: /code
    command: npm start
    depends_on:
      - db

  client:
    container_name: react-client-app
    image: node:12-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./client:/code:delegated
    networks:
      - reactapp-network
    working_dir: /code
    command: npm start

  worker:
    image: node:12-alpine
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
    volumes:
      - ./worker:/code:delegated
    networks:
      - reactapp-network
    working_dir: /code
    command: npm start
    depends_on:
      - db

  db:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - reactapp-network
    ports:
      - "27018:27017"

  redis:
    container_name: cache
    image: "redis:alpine"
    networks:
      - reactapp-network
    ports:
      - "6379:6379"

networks:
  reactapp-network:
    driver: bridge
